# Generated by Django 5.0.14 on 2025-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
