# Generated by Django 5.2.6 on 2025-09-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='last_login',
        ),
    ]
