# Generated by Django 5.2.6 on 2025-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentaccount_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
