# Generated by Django 5.2.6 on 2025-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentaccount_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
