# Generated by Django 5.0.14 on 2025-11-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentaccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payments', to='accounts.request'),
        ),
    ]
