# Generated by Django 5.2.6 on 2025-10-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentaccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
