# Generated by Django 5.2.6 on 2025-09-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentaccount_student_id_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='username',
        ),
    ]
