# Generated by Django 5.0.14 on 2025-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_request_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment_receipt',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
