# Generated by Django 5.2.6 on 2025-10-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentaccount_username'),
        ('accounts', '0004_studentaccount_program'),
    ]

    operations = [
    ]
