# Generated by Django 6.0 on 2025-12-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_request_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by', to='accounts.adminaccount'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_verified_by', to='accounts.adminaccount'),
        ),
        migrations.AddField(
            model_name='request',
            name='ready_for_pickup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_for_pickup_by', to='accounts.adminaccount'),
        ),
        migrations.AddField(
            model_name='request',
            name='requirements_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_verified_by', to='accounts.adminaccount'),
        ),
    ]
