# Generated by Django 6.0 on 2025-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_request_completed_by_request_payment_verified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='payment_feedback',
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
