# Generated by Django 6.0 on 2025-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_request_payment_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
