# Generated by Django 6.0 on 2025-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_paymentupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementupload',
            name='delete_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirementupload',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
